#!/bin/bash
#./tsp_p.e -m -i in/gr_kinder4_lpd   -o out/gr_kinder4_lpd.META_HEUR.out
#./tsp_p.e -m -i in/gr_ulysses23_lpd -o out/gr_ulysses23_lpd.META_HEUR.out
#./tsp_p.e -m -i in/gr_berlin51_lpd  -o out/gr_berlin51_lpd.META_HEUR.out
./tsp_p.e  -m  -i in/gr_teste   -o out/gr_test.META_HEUR.out
